// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB90UsLkaQLC3Hki-O6yngaq11n1tqOLzA',
    appId: '1:432894218802:web:28cb579c770c383024622b',
    messagingSenderId: '432894218802',
    projectId: 'travelling-app-2776a',
    authDomain: 'travelling-app-2776a.firebaseapp.com',
    storageBucket: 'travelling-app-2776a.firebasestorage.app',
    measurementId: 'G-GHRKSJ3VLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSaMtWjaNHyFATFmLsnLB6hTefSMMkUhA',
    appId: '1:432894218802:android:aebac0e9a58bddfb24622b',
    messagingSenderId: '432894218802',
    projectId: 'travelling-app-2776a',
    storageBucket: 'travelling-app-2776a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQ7sf-6UnjQgatD0m_CVtTyX_dvlz4NM',
    appId: '1:432894218802:ios:0191318942bcb0d124622b',
    messagingSenderId: '432894218802',
    projectId: 'travelling-app-2776a',
    storageBucket: 'travelling-app-2776a.firebasestorage.app',
    iosBundleId: 'com.example.tailorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQ7sf-6UnjQgatD0m_CVtTyX_dvlz4NM',
    appId: '1:432894218802:ios:0191318942bcb0d124622b',
    messagingSenderId: '432894218802',
    projectId: 'travelling-app-2776a',
    storageBucket: 'travelling-app-2776a.firebasestorage.app',
    iosBundleId: 'com.example.tailorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB90UsLkaQLC3Hki-O6yngaq11n1tqOLzA',
    appId: '1:432894218802:web:6df9bc0096d4e88324622b',
    messagingSenderId: '432894218802',
    projectId: 'travelling-app-2776a',
    authDomain: 'travelling-app-2776a.firebaseapp.com',
    storageBucket: 'travelling-app-2776a.firebasestorage.app',
    measurementId: 'G-T0WBQRBX94',
  );
}
